#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#Navegamos al directorio raiz del proyecto 
cd "$(dirname "$0")/.."

echo "Buildeando la aplicación"
dotnet build TiendaTaller.csproj --no-restore --verbosity quiet

echo "Chequeo del pre-push completado"